modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/ZsoltMolnarrr/Critical-Strike/issues"
license = "GPL-3.0"

[[mods]]
modId = "critical_strike"
version = "${version}"
displayName = "Critical Strike"
authors = "Daedelus"
description = '''
Chance based critical hits for melee and ranged attacks!
'''
logoFile = "icon.png"

[[dependencies.critical_strike]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.critical_strike]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_compat_version},)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "critical_strike.mixins.json"
